/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.trenajer_apache;


import java.awt.BasicStroke;
import java.awt.Graphics;
import java.awt.Graphics2D;
import static java.lang.Thread.sleep;
/**
 *
 * @author retyr
 */
public class panel_my extends javax.swing.JPanel {

   public int x1=0;
   public int x2=25;
   public int x3=25;
   public int endx4=30;
   public int y1=100;
   public int y2=95;
   public int y3=105;
   public int endy4=100;
    
   public int xOV=390;
   public int xOV2=275;
   public int yOV=90;
   public int yOV2=80;
   public int r=10;
   
   public int temp=0;
    
   private int newy1=0;
   private int newy2=0;
   
    public int quad(int a) {
        return a*a;
    }
    private void mycircle1(int x, int y){
    
    this.xOV2=x;
    this.yOV2=y;
    this.repaint();
    }
    private void mycircle2(int x, int y){
    this.xOV=x;
    this.yOV=y;
    this.repaint();
    }
    public void stopgame(){
        mycircle1(275,80);
        mycircle2(390,90);
        myArrow(0,25,25,30,100,95,105,100);
    
    }
    public void myArrow(int x1, int x2, int x3,int x4,int y1, int y2, int y3, int y4 ){
    
        this.x1=x1;
        this.x2=x2;
        this.x3=x3;
        this.endx4=x4;
        
        this.y1=y1;
        this.y2=y2;
        this.y3=y3;
        this.endy4=y4;
    
        this.repaint();
    
    }
    public void nextyOV1() throws InterruptedException{
        
         this.newy1=yOV2;
         
        boolean flag=true;
        while(flag){
            newy1=yOV2+1;
            sleep(10);
            mycircle1(xOV2,newy1);
            if(newy1+r>this.getHeight()-5&& !(newy1+r<this.getHeight()-5)){
                flag=false;
            }            
        }
        while(flag==false){
        newy1=yOV2-1;
        sleep(10);
        mycircle1(xOV2,newy1);
           if(newy1+r<5 &&!(newy1+r>5)) {
               flag=true;
           }
        }
        
    }
    public void nextyOV2() throws InterruptedException{
        
         this.newy2=yOV;
         
        boolean flag=true;
        while(flag){
            newy2=yOV+2;
            sleep(10);
            mycircle2(xOV,newy2);
            if(newy2+r>this.getHeight()-5&& !(newy2+r<this.getHeight()-5)){
                flag=false;
            }            
        }
        while(flag==false){
        newy2=yOV-2;
        sleep(10);
        mycircle2(xOV,newy2);
           if(newy2+r<5 &&!(newy2+r>5)) {
               flag=true;
           }
        }
        
    }
    public void nextx(){
        
       int  newx1=x1+5;
        int newx2=x2+5;
        int newx3=x3+5;
        int newx4=endx4+5;
        if(quad(xOV2-newx4)+quad(yOV2-endy4)<=(r*4-10)*(r*4-10)){
            this.temp+=1;
            newx1=0;
            newx2=25;
            newx3=25;
            newx4=30;
        }
        else if(quad(xOV-newx4)+quad(yOV-endy4)<=(r*2)*(r*2)){
            this.temp+=2;
            newx1=0;
            newx2=25;
            newx3=25;
            newx4=30;
        }
        else if(newx4>this.getWidth()){
            newx1=0;
            newx2=25;
            newx3=25;
            newx4=30;
        }
        
      
        myArrow(newx1,newx2,newx3,newx4,y1,y2,y3,endy4);
    }
    
    public panel_my() {
        initComponents();
    }
    public void arrow(Graphics g,int x1, int x2, int x3,int x4,int y1, int y2, int y3, int y4 ){   
     g.drawLine(x1, y1, x4, y4);
     g.drawLine(x2, y2, x4, y4);
     g.drawLine(x3, y3, x4, y4);
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

@Override
    protected void paintComponent(Graphics g){
      
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
         Graphics2D g2d = (Graphics2D) g;
         
         g2d.setStroke(new BasicStroke(3));
         
        
         g2d.drawLine(400, 0, 400, 200);
         g2d.drawLine(300, 0, 300, 200);
         g2d.drawOval(xOV, yOV, r*2, r*2);
         g2d.drawOval(xOV2, yOV2, r*4, r*4);
        arrow(g2d,x1,x2,x3,endx4,y1,y2,y3,endy4);
        
         
         
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
